name: very_good_core_hooks

on:
  pull_request:
    paths:
      - ".github/workflows/very_good_core_hooks.yaml"
      - "brick/hooks/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/very_good_core_hooks.yaml"
      - "brick/hooks/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      working_directory: "brick/hooks"
      analyze_directories: "test"
      report_on: "pre_gen.dart"
